### ISSUE TITLE
Update database tables

### ISSUE THREAD

**Issue by ann760** [ahmadelgamal/ucb-my-food-choices#14]
UI changes will need updates to the database tables
The new table will include user, restriction, and profile. 
The session table is created as part of the authentication.

**Comment by ahmadelgamal** [comment]
@ann760, I'm not sure what needs to change in the UI. Please clarify.

**Comment by ann760** [comment]
The UI changes were already made.  We removed events and added profile.  now the databases and seeds match. 
This is done!
